# Generated by Django 5.2.1 on 2025-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='content'),
        ),
    ]
