# Generated by Django 5.2.1 on 2025-05-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlecomment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
